export const PRODUCT_DETAILS = "PRODUCT_DETAILS";
export const CART_DETAILS = "CART_DETAILS";
export const CART_ADD_DETAILS = "CART_ADD_DETAILS";
export const CART_REMOVE_DETAILS = "CART_REMOVE_DETAILS";
export const CART_INCREMENT_DETAILS = "CART_INCREMENT_DETAILS";
export const CART_DECREMENT_DETAILS = "CART_DECREMENT_DETAILS";
export const HANDLE_CHECKOUT_DETAILS = "HANDLE_CHECKOUT_DETAILS";